Repository PapillonApp/Papillon, pull requests merged in 2024-12, with the labels that each got.

#518 Prise en compte des valeurs "~" renvoyer par Scodoc IUT Lannion
  src/services/iutlan/grades.ts
Labels: ❌ error

#514 Luminosité de l'écran QRCode
  src/views/account/Restaurant/Modals/QrCode.tsx
  src/views/settings/ExternalAccount/Turboself.tsx
Labels: 🪱 bug

#519 Fix : Gestion des présences et optimisation du code
  src/services/iutlan/attendance.ts
Labels: 🪱 bug

#478 fix(lessons) : Display 'Aucun' when no teacher is assigned to a lesson
  src/views/account/Lessons/Document.tsx
Labels: 🪱 bug

#402 feat(account): Ajout des informations d'identité
  src/stores/account/types.ts
  src/views/login/IdentityProvider/actions/BackgroundIUTLannion.tsx
  src/views/settings/SettingsProfile.tsx
Labels: ✨ enhancement

#535 Better Home Lessons
  src/services/pronote/chats.ts
  src/utils/format/holidayEmoji.ts
  src/views/account/Home/Elements/TimetableElement.tsx
  src/views/account/Lessons/Atoms/Page.tsx
Labels: ✨ enhancement, 🚸 user experience

#462 Ajout du contenu de cours
  package-lock.json
  package.json
  src/providers/AlertProvider.tsx
  src/services/pronote/chats.ts
  src/services/pronote/timetable.ts
  src/services/shared/Timetable.ts
  src/views/account/Lessons/Document.tsx
Labels: ✨ enhancement

#487 Sélection de compte Turboself
  src/router/helpers/types.ts
  src/router/screens/settings/index.ts
  src/services/turboself/reload.ts
  src/views/settings/ExternalAccount/IzlyActivation.tsx
  src/views/settings/ExternalAccount/PriceDetectionOnboarding.tsx
  src/views/settings/ExternalAccount/Turboself.tsx
  src/views/settings/ExternalAccount/TurboselfAccountSelector.tsx
Labels: ✨ enhancement
