Repository PapillonApp/Papillon, pull requests merged in 2024-11, with the labels that each got.

#277 Implémentation de TurboSelf
  babel.config.js
  package-lock.json
  package.json
  src/components/Restaurant/RestaurantCard.tsx
  src/router/helpers/types.ts
  src/router/screens/account/index.tsx
  src/services/balance.ts
  src/services/booking.ts
  src/services/menu.ts
  src/services/pronote/menu.ts
  src/services/qrcode.ts
  src/services/reload-account.ts
  src/services/reservation-history.ts
  src/services/shared/Booking.ts
  src/services/shared/ReservationHistory.ts
  src/services/turboself/balance.ts
  src/services/turboself/booking.ts
  src/services/turboself/history.ts
  src/services/turboself/qrcode.ts
  src/services/turboself/reload.ts
  src/stores/account/types.ts
  src/views/account/Restaurant/Menu.tsx
  src/views/account/Restaurant/Modals/History.tsx
  src/views/account/Restaurant/Modals/QrCode.tsx
  src/views/settings/ExternalAccount/Turboself.tsx
  src/views/settings/Settings.tsx
  src/widgets/Components/RestaurantBalance.tsx
  src/widgets/Components/RestaurantQRCode.tsx
  src/widgets/index.tsx
Labels: ✨ enhancement, 🔌 ENT / services

#362 feat(grades): Ajout de la moyenne de classe renvoyée par Pronote si elle est disponible
  src/views/account/Grades/Grades.tsx
  src/views/account/Grades/Graph/GradesAverage.tsx
Labels: ✨ enhancement, 🪱 bug

#281 Feat(News): intégration "J'ai pris connaissance..." + changes
  src/components/Global/PapillonPicker.tsx
  src/router/screens/views/index.ts
  src/utils/magic/categorizeMessages.ts
  src/views/account/News/Atoms/Item.tsx
  src/views/account/News/Document.tsx
  src/views/account/News/News.tsx
Labels: ✨ enhancement, 🚸 user experience
