Repository PapillonApp/Papillon, pull requests merged in 2024-09, with the labels that each got.

#119 [Feature]: ajout de l'Université de Limoges pour les identity providers
  assets/images/service_unilim.png
  package-lock.json
  package.json
  src/router/helpers/types.ts
  src/router/screens/login/identityProvider.ts
  src/services/local/default-personalization.ts
  src/views/login/IdentityProvider/IdentityProviderSelector.tsx
  src/views/login/IdentityProvider/providers/UnivLimoges.tsx
  src/views/login/IdentityProvider/providers/UnivRennes1.tsx
Labels: ✨ enhancement

#171 feat(NextCourseWidget): Add a link to timetable
  src/widgets/Components/NextCourse.tsx
Labels: ✨ enhancement, 🚸 user experience

#170 fix(Home): card height not correctly set
  src/views/account/Home/Home.tsx
Labels: 🪱 bug, 🚸 user experience

#179 Add widget to display the latest obtained grade
  src/views/account/Home/Home.tsx
  src/widgets/Components/LastGrade.tsx
  src/widgets/index.tsx
Labels: ✨ enhancement, 🎨 interface, 🚸 user experience

#175 Fixs mineurs
  src/views/settings/Settings.tsx
  src/views/settings/SettingsTabs.tsx
Labels: ✨ enhancement

#158 ✨ [Homework] : Ajout du sélecteur de date et d'un panneau de réglage de l'onglet - 🚨 iOS ONLY 🚨
  src/views/account/Homeworks/Homeworks.tsx
Labels: ✨ enhancement, 🎨 interface, 🚸 user experience

#184 style(Homeworks): update text color for completed items
  src/views/account/Homeworks/Atoms/Item.tsx
Labels: ✨ enhancement, 🎨 interface

#192 fix(homeworks) : Rewrite of homeworks for stability and performance
  src/components/Global/PapillonCheckbox.tsx
  src/components/Global/PapillonSpinner.tsx
  src/router/screens/account/index.tsx
  src/utils/ui/animations.ts
  src/views/account/Homeworks/Atoms/Item.tsx
  src/views/account/Homeworks/Homeworks.old.tsx
  src/views/account/Homeworks/Homeworks.tsx
Labels: 🪱 bug, 🚸 user experience

#197 feat(widgets): Add useCallback hook to improve performance + RealTime in NextCourse.tsx
  src/widgets/Components/NextCourse.tsx
Labels: ✨ enhancement, 🎨 interface

#187 style(Lessons) : red backgroung and color when a teacher is absent
  src/views/account/Lessons/Atoms/Item.tsx
Labels: ✨ enhancement, 🎨 interface

#189 fix(home): plusieurs changements
  src/router/screens/index.ts
  src/views/account/Home/Elements/HomeworksElement.tsx
  src/views/account/Home/Elements/TimetableElement.tsx
Labels: ✨ enhancement, 🪱 bug, 🚸 user experience

#198 feat(lessons): New UI for lessons based on homeworks changes
  src/components/Global/PapillonModernHeader.tsx
  src/views/account/Lessons/Atoms/Page.tsx
  src/views/account/Lessons/Lessons.tsx
  src/views/account/Lessons/LessonsHeader.tsx
Labels: ✨ enhancement, 🪱 bug, 🎨 interface, 🚸 user experience

#199 feat(homeworks): Ajout des liens, des pièces jointes et des modals
  package-lock.json
  package.json
  src/router/helpers/types.ts
  src/router/screens/views/index.ts
  src/views/account/Home/Elements/HomeworksElement.tsx
  src/views/account/Home/Home.tsx
  src/views/account/Homeworks/Atoms/Item.tsx
  src/views/account/Homeworks/Document.tsx
  src/views/account/Homeworks/Homeworks.tsx
Labels: ✨ enhancement, 🎨 interface, 🚸 user experience

#188 Ajout des données de Skolengo dans l'app
  src/services/attendance.ts
  src/services/grades.ts
  src/services/homework.ts
  src/services/news.ts
  src/services/pronote/timetable.ts
  src/services/reload-account.ts
  src/services/shared/Period.ts
  src/services/shared/Timetable.ts
  src/services/shared/errors.ts
  src/services/skolengo/data/attachment.ts
  src/services/skolengo/data/attendance.ts
  src/services/skolengo/data/grades.ts
  src/services/skolengo/data/homework.ts
  src/services/skolengo/data/news.ts
  src/services/skolengo/data/period.ts
  src/services/skolengo/data/timetable.ts
  src/services/skolengo/data/utils.ts
  src/services/skolengo/default-personalization.ts
  src/services/skolengo/reload-skolengo.ts
  src/services/skolengo/skolengo-account.ts
  src/services/skolengo/skolengo-types.ts
  src/services/timetable.ts
  src/stores/account/index.ts
  src/stores/account/types.ts
  src/views/account/Lessons/Atoms/Item.tsx
  src/views/login/ServiceSelector.tsx
  src/views/login/skolengo/SkolengoInstanceSelector.tsx
  src/views/login/skolengo/SkolengoWebview.tsx
  src/views/welcome/AccountCreated.tsx
  src/widgets/Components/NextCourse.tsx
Labels: 🔌 ENT / services

#195 feat: Ajout des notes de mise à jour
  src/components/Global/NativeComponents.tsx
  src/consts/datasets.json
  src/router/helpers/types.ts
  src/router/screens/welcome/index.ts
  src/views/account/Home/Home.tsx
  src/views/welcome/ChangelogScreen.tsx
  src/views/welcome/test.json
Labels: ✨ enhancement

#205 feat: Illustrations sur le sélecteur de compte
  src/components/Global/NativeComponents.tsx
  src/consts/datasets.json
  src/views/welcome/AccountSelector.tsx
  src/views/welcome/DevMenu.tsx
Labels: 🎨 interface, 🚸 user experience

#217 Ajout d'une margin au check de sélection de la période de note
  src/components/Global/PapillonPicker.tsx
Labels: 🪱 bug, 🎨 interface

#185 Style + added links + auto https
  src/components/Home/Header.tsx
  src/services/pronote/determinate-authentication-view.tsx
  src/views/login/pronote/PronoteAuthenticationSelector.tsx
  src/views/login/pronote/PronoteGeolocation.tsx
  src/views/login/pronote/PronoteManualLocation.tsx
  src/views/login/pronote/PronoteManualURL.tsx
  src/views/login/skolengo/SkolengoAuthenticationSelector.tsx
  src/views/login/skolengo/SkolengoGeolocation.tsx
  src/views/settings/Settings.tsx
  src/views/welcome/AccountCreated.tsx
  src/views/welcome/FirstInstallation.tsx
  src/widgets/Components/GeneralAverage.tsx
  src/widgets/Components/NextCourse.tsx
Labels: ✨ enhancement
