Repository PapillonApp/Papillon, pull requests merged in 2024-10, with the labels that each got.

#238 chore: Refactor Lessons component to use FlatList for improved perfor…
  src/views/account/Lessons/Lessons.tsx
Labels: ✨ enhancement

#258 [PRONOTE]: Ajout des code pin pour toutes les méthodes d'auth
  src/views/login/pronote/PronoteQRCode.tsx
  src/views/login/pronote/PronoteV6Import.tsx
  src/views/login/pronote/PronoteWebview.tsx
Labels: ✨ enhancement, 🔌 ENT / services

#276 Ajouts des universités au README
  README.md
Labels: 📘 documentation

#273 feat(service): Ajout de l'Université Polytechnique Haut-de-France
  assets/images/service_uphf.png
  package-lock.json
  package.json
  src/router/helpers/types.ts
  src/router/screens/login/identityProvider.ts
  src/services/news.ts
  src/services/reload-account.ts
  src/services/shared/errors.ts
  src/services/timetable.ts
  src/services/uphf/data/news.ts
  src/services/uphf/data/timetable.ts
  src/services/uphf/default-personalization.ts
  src/services/uphf/reload-uphf.ts
  src/stores/account/types.ts
  src/views/login/IdentityProvider/providers/UnivUphf.tsx
Labels: ✨ enhancement, 🔌 ENT / services

#270 Feat(Lessons): affichage des DS + fix
  src/services/pronote/timetable.ts
  src/services/shared/Timetable.ts
  src/views/account/Lessons/Atoms/Item.tsx
  src/views/account/Lessons/Document.tsx
Labels: ✨ enhancement, 🎨 interface

#271 Fix(News): affichage plein de fois de "Aucune actualité"
  src/utils/format/format_date_complets.ts
  src/views/account/News/News.tsx
Labels: ✨ enhancement, 🪱 bug

#257 Fix(Grades): Inversion -/+
  src/views/account/Grades/Document.tsx
Labels: 🪱 bug

#274 Fix(newCompte): 3 changes
  src/components/FirstInstallation/DuoListPressable.tsx
  src/router/screens/login/index.ts
  src/views/login/ServiceSelector.tsx
Labels: ✨ enhancement, 🪱 bug

#267 [Fix]: Initiales non correspondantes dans les actus
  src/views/account/News/Document.tsx
Labels: 🪱 bug

#215 feat: Moving finished homework to the bottom of the day
  src/views/account/Homeworks/Homeworks.tsx
Labels: ✨ enhancement, 🎨 interface

#241 fix(Home) : Affichage des devoirs de la semaine prochaine le week-end
  src/views/account/Home/Elements/HomeworksElement.tsx
  src/widgets/Components/NextCourse.tsx
Labels: 🪱 bug

#246 feat(tabs): Many changes
  src/components/Global/PapillonPicker.tsx
  src/components/Home/Header.tsx
  src/router/helpers/PapillonTabNavigator.tsx
  src/views/settings/Settings.tsx
  src/views/settings/SettingsTabs.tsx
Labels: ✨ enhancement, 🎨 interface, 🚸 user experience

#263 Divers fixs de typo
  src/views/account/Grades/Atoms/GradeTitle.tsx
  src/views/account/Grades/Document.tsx
  src/views/account/Grades/Latest/LatestGradesItem.tsx
  src/views/account/Lessons/Document.tsx
Labels: ✨ enhancement

#285 Devoirs Intelligents
  src/services/ecoledirecte/default-personalization.ts
  src/services/local/default-personalization.ts
  src/services/pronote/default-personalization.ts
  src/services/skolengo/default-personalization.ts
  src/stores/account/types.ts
  src/utils/magic/categorizeHomeworks.ts
  src/utils/magic/regex/evaldetection.json
  src/views/account/Homeworks/Atoms/Item.tsx
  src/views/account/Lessons/Document.tsx
  src/views/account/News/News.tsx
  src/views/settings/SettingsMagic.tsx
Labels: ✨ enhancement

#286 Feat+Fix(uphf): Ajout de la photo de profil
  package-lock.json
  package.json
  src/services/uphf/default-personalization.ts
  src/views/login/IdentityProvider/IdentityProviderSelector.tsx
  src/views/login/IdentityProvider/providers/UnivUphf.tsx
Labels: ✨ enhancement, 🎨 interface

#297 feat(Pronote): Popup informative
  src/views/login/pronote/PronoteWebview.tsx
Labels: ✨ enhancement, 🎨 interface, 🔌 ENT / services

#298 Refactor HomeworksElement to handle empty hwFinalList and hwFinalList2
  src/views/account/Home/Elements/HomeworksElement.tsx
Labels: ✨ enhancement, 🔌 ENT / services

#295 Fix(Grades): changes + many fix
  src/utils/grades/getAverages.ts
  src/views/account/Grades/Document.tsx
  src/views/account/Grades/Grades.tsx
  src/views/account/Grades/Graph/GradesAverage.tsx
  src/views/account/Grades/Latest/LatestGrades.tsx
  src/views/account/Grades/Latest/LatestGradesItem.tsx
  src/views/account/Grades/Modals/Subject.tsx
  src/views/account/Grades/Subject/GradeItem.tsx
  src/views/account/Grades/Subject/SubjectList.tsx
  src/views/account/Home/Elements/GradesElement.tsx
  src/widgets/Components/GeneralAverage.tsx
Labels: ✨ enhancement, 🪱 bug

#303 🧹 Rewrite de la page d'accueil
  src/components/Home/AccountSwitcher.tsx
  src/components/Home/Widget.tsx
  src/views/account/Home/Animations/HomeAnimations.tsx
  src/views/account/Home/ElementIndex.tsx
  src/views/account/Home/Elements/AttendanceElement.tsx
  src/views/account/Home/Elements/GradesElement.tsx
  src/views/account/Home/Elements/HomeworksElement.tsx
  src/views/account/Home/Elements/PopupRestauration.tsx
  src/views/account/Home/Elements/TimetableElement.tsx
  src/views/account/Home/Home.tsx
  src/views/account/Home/ModalContent.tsx
  src/widgets/Components/NextCourse.tsx
Labels: ✨ enhancement, 🎨 interface

#292 fix(ios): fix ios build issue due to wrong files location
  ios/Papillon/FilePreviewManager.h
  ios/Papillon/FilePreviewManager.m
Labels: ✨ enhancement, 🪱 bug

#296 ed: various fixes & enhancements part 2
  package.json
  src/router/screens/account/index.tsx
  src/services/ecoledirecte/attendance.ts
  src/services/ecoledirecte/timetable.ts
  src/views/account/Home/Elements/HomeworksElement.tsx
Labels: ✨ enhancement, 🔌 ENT / services
