Repository PapillonApp/Papillon, pull requests merged in 2025-09, with the labels that each got.

#302 fix: correction de plusieurs bugs
  app/(modals)/course.tsx
  app/(settings)/magic.tsx
  app/(settings)/settings.tsx
  app/(tabs)/grades/index.tsx
  app/(tabs)/index/index.tsx
  ios/Papillon/Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png
  locales/en.json
  locales/fr.json
  package-lock.json
  package.json
Labels: status: needs triage

#324 feat: Avatar component and Skeleton property
  app/(settings)/settings.tsx
  app/(tabs)/profile/custom.tsx
  app/(tabs)/profile/index.tsx
  app/demo.tsx
  ui/components/Avatar.tsx
  ui/components/CompactGrade.tsx
  ui/components/Course.tsx
  ui/components/Grade.tsx
  ui/components/Icon.tsx
  ui/components/SkeletonView.tsx
  ui/components/Subject.tsx
  ui/components/Task.tsx
  ui/components/Typography.tsx
Labels: area: ui, status: approved, status: invalid, status: needs triage, type: enhancement

#325 Fix/androbug
  app/(features)/attendance.tsx
  app/(onboarding)/end/color.tsx
  app/(onboarding)/skolengo/webview.tsx
  app/(settings)/personalization.tsx
  app/(settings)/subject_personalization.tsx
  app/(tabs)/index/index.tsx
  app/(tabs)/profile/index.tsx
  app/(tabs)/tasks/index.tsx
  locales/fr.json
  services/ecoledirecte/attendance.ts
  services/ecoledirecte/chat.ts
  services/ecoledirecte/grades.ts
  services/ecoledirecte/homework.ts
  services/ecoledirecte/news.ts
  services/ecoledirecte/timetable.ts
  services/turboself/balance.ts
  services/turboself/booking.ts
  services/turboself/history.ts
  services/turboself/index.ts
  services/turboself/qrcode.ts
  services/turboself/refresh.ts
  ui/components/AnimatedPressable.tsx
  utils/week.ts
Labels: area: i18n, area: ui, status: invalid, status: needs triage, type: bug, area: backend

#393 Click on contributor profile open a page with github page
  app/(settings)/about.tsx
  app/(settings)/personalization.tsx
Labels: area: ui, status: approved, type: enhancement

#429 feat(database): Implement safe transaction handling and database initialization logic
  app/_layout.tsx
  database/DatabaseProvider.tsx
  database/index.ts
  database/useAttendance.ts
  database/useBalance.ts
  database/useCanteen.ts
  database/useChat.ts
  database/useGrades.ts
  database/useHomework.ts
  database/useIcals.ts
  database/useKids.ts
  database/useNews.ts
  database/useSubject.ts
  database/useTimetable.ts
  database/utils/initialization.ts
  database/utils/safeTransaction.ts
Labels: status: needs review, type: enhancement, area: backend, area: cache

#405 New Crowdin updates
  locales/de.json
  locales/en.json
  locales/es.json
  locales/tr.json
Labels: status: invalid, status: needs triage
